// @generated by protoc-gen-es v1.7.1 with parameter "target=ts"
// @generated from file apps/backend/auth/src/proto/auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum auth.UserRole
 */
export enum UserRole {
  /**
   * @generated from enum value: USER = 0;
   */
  USER = 0,

  /**
   * @generated from enum value: ADMIN = 1;
   */
  ADMIN = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(UserRole)
proto3.util.setEnumType(UserRole, "auth.UserRole", [
  { no: 0, name: "USER" },
  { no: 1, name: "ADMIN" },
]);

/**
 * @generated from message auth.Payload
 */
export class Payload extends Message<Payload> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: int32 exp = 2;
   */
  exp = 0;

  /**
   * @generated from field: int32 iat = 3;
   */
  iat = 0;

  constructor(data?: PartialMessage<Payload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "auth.Payload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "exp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "iat", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Payload {
    return new Payload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Payload {
    return new Payload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Payload {
    return new Payload().fromJsonString(jsonString, options);
  }

  static equals(a: Payload | PlainMessage<Payload> | undefined, b: Payload | PlainMessage<Payload> | undefined): boolean {
    return proto3.util.equals(Payload, a, b);
  }
}

/**
 * @generated from message auth.UserEntity
 */
export class UserEntity extends Message<UserEntity> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string firstName = 2;
   */
  firstName = "";

  /**
   * @generated from field: string lastName = 3;
   */
  lastName = "";

  /**
   * @generated from field: string username = 4;
   */
  username = "";

  /**
   * @generated from field: string email = 6;
   */
  email = "";

  /**
   * @generated from field: bool verified = 7;
   */
  verified = false;

  /**
   * @generated from field: string role = 8;
   */
  role = "";

  /**
   * @generated from field: string hashedRefreshToken = 9;
   */
  hashedRefreshToken = "";

  constructor(data?: PartialMessage<UserEntity>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "auth.UserEntity";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "firstName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "lastName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "hashedRefreshToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserEntity {
    return new UserEntity().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserEntity {
    return new UserEntity().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserEntity {
    return new UserEntity().fromJsonString(jsonString, options);
  }

  static equals(a: UserEntity | PlainMessage<UserEntity> | undefined, b: UserEntity | PlainMessage<UserEntity> | undefined): boolean {
    return proto3.util.equals(UserEntity, a, b);
  }
}

