import { createTheme, MantineProvider } from '@mantine/core';
import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'cyan',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-backgroundColor">
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
